### ISSUE TITLE
looks really nice: can you add some usage instructions?

### ISSUE THREAD

**Issue by sg-s** [rocheio/huge-gmaps#1]
- how do I figure out which area on the screen to crop?
- I see there is an overlap between adjacent tiles. is there a way to find the parameter that removes this overlap without trial and error?

thanks!

**Comment by rocheio** [comment]
Added some more detailed instructions to the README. Unfortunately there's a good amount of trial-and-error involved, both to find the cropping offsets for your given computer, and to remove the overlap.

I had to run a lot of 1x2 and 2x1 tests to find the magic latitude/longitude shift numbers originally, but I found that once a 3x3 lined up perfectly, they were good enough to apply to a 20+ screenshot grid without drift.

If you can let me know the setup / numbers that end up working for you, I'll take a look at the formula and see how it could be adjusted to work for both of us.

**Comment by sg-s** [comment]
thanks, will do!
